### ISSUE TITLE
Model scheduled for release march 2023 but still no models? 

### ISSUE THREAD

**Issue by spacewalkingninja** [shinhyeokoh/rwen#3]
Can you kindly explain how to adapt this to any ither (for example on top of a coqui-tts which uses vits) or just release the models as they were supposedly _Scheduled to be released_ so we can start using this industrially. Thanks a lot <3

**Comment by shinhyeokoh** [comment]
Hello :)

We did not plan to release the model checkpoint from the beginning.

Currently, we released the code corresponding to rwen.

It can be reproduced by appropriately combining the rwen code based on the repository of the tts model (e.g. fastpitch, vits).

I'll discuss with the co-author how to modify the readme to kindly explain.

**Comment by spacewalkingninja** [comment]
Yeah, just leaving us dead-in-the-water people who don't have powerfull GPU's and are poor and can't pay for GPU time or pay to buy a GPU. Very democratic.. :(
